### ISSUE TITLE
Add the models of database

### ISSUE THREAD

**Issue by MorganLug** [StudentGamingNetwork/website#17]
TODO : 
* Get Database design choices
* Use knex and create appropriate ts files

**Comment by TheHerobrine** [comment]
Happy to see that you already created an issue for this 😄 !

Though, I think you should focus on creating one table at a time to match our need, and not the whole thing in one issue 😉.

For now, I created two tables for the base of architecture:
- users
- sessions

You can take a look at their creation script in `backend/src/database/migrations`.

Normally you should never modify a migration script once it's on master, but since there's no prod database for now, you can modify them (to add some fields, maybe add a relation between the two...)

I suggest you make a few search to see if GraphQL is the best approach for our needs (I'm still not 100% sure 😅), and if it is, try to migrate the few routes already implemented 😉 (they are in `/src/module/user/handler.ts`).
